version: '3.7'

services:
  nginx:
    image: nginx:1.23.2
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - ugc.kafka
      - ugc.kafka-ui
      - clickhouse-node1
      - ugc_api
      - etl
    ports:
      - "80:80"

  ugc.zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0-3-ubi8
    hostname: ugc.zookeeper
    container_name: ugc.zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ugc.kafka:
    image: confluentinc/cp-kafka:6.2.0-3-ubi8
    hostname: ugc.kafka
    container_name: ugc.kafka
    depends_on:
      - ugc.zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ugc.zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ugc.kafka:9092,PLAINTEXT_HOST://localhost:31204
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 10
    restart: on-failure

  ugc.kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: ugc.kafka-ui
    container_name: ugc.kafka-ui
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ugc.kafka:9092
      KAFKA_CLUSTERS_0_NAME: ugc.kafka
      KAFKA_CLUSTERS_0_ZOOKEEPER: ugc.zookeeper:2181
    ports:
      - "31205:8080"

  ugc_api:
    container_name: ugc_api
    build:
      context: ./ugc/src
    env_file:
      - ./.env
    depends_on:
      - ugc.kafka
    restart: on-failure

  clickhouse-node1:
    image: yandex/clickhouse-server:21.3
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    volumes:
      - ./clickhouse/node1:/etc/clickhouse-server
    depends_on:
      - ugc.zookeeper

  clickhouse-node2:
    image: yandex/clickhouse-server:21.3
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./clickhouse/node2:/etc/clickhouse-server
    depends_on:
      - ugc.zookeeper

  clickhouse-node3:
    image: yandex/clickhouse-server:21.3
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./clickhouse/node3:/etc/clickhouse-server
    depends_on:
      - ugc.zookeeper
  clickhouse-node4:
    image: yandex/clickhouse-server:21.3
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./clickhouse/node4:/etc/clickhouse-server
    depends_on:
      - ugc.zookeeper


  etl:
    container_name: etl
    build:
      context: ./etl
    env_file:
      - ./.env
    depends_on:
      - clickhouse-node1
      - ugc.kafka
    restart: on-failure