name: Python application

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy isort flake8
    
    - name: black
      run: black --check --line-length=119 .

    - name: isort
      run: isort --check --line-length=119 --profile=black .
    
    - name: flake8
      run: flake8 --config=setup.cfg

    - name: mypy_ugc
      run: mypy ugc 
    - name: mypy_etl
      run: mypy etl

    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          repository: ${{github.repository}}
          Python ${{ matrix.python-version }}
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
